[workspace]
resolver = "2"
members = ["rpc-api", "server", "webapp"]
default-members = ["rpc-api", "server"]

[workspace.package]
authors = [
    "Ash Manning <ash@layertwolabs.com>",
]
edition = "2024"
publish = false
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.71"
futures = { version = "0.3.31", default-features = false }
jsonrpsee = "0.25.1"
serde_json = "1.0.145"

[workspace.dependencies.bitnames-types]
git = "https://github.com/LayerTwo-Labs/plain-bitnames.git"
rev = "9a8acbfa0cccdc764ee7f0f78869556034f3eb11"
package = "plain_bitnames_types"

[workspace.dependencies.bitnames-rpc-api]
git = "https://github.com/LayerTwo-Labs/plain-bitnames.git"
rev = "9a8acbfa0cccdc764ee7f0f78869556034f3eb11"
package = "plain_bitnames_app_rpc_api"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
assertions_on_result_states = "allow"
let_unit_value = "allow"
print_stderr = "deny"
print_stdout = "deny"
significant_drop_in_scrutinee = "deny"
significant_drop_tightening = "deny"
wildcard_imports = "deny"

[workspace.lints.rust]
let_underscore_drop = "deny"
