[package]
name = "bitnames-tg-webapp"
authors.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[build-dependencies]
grass = "0.13.4"

[dependencies]
anyhow = { workspace = true }
bitnames-tg-rpc-api = { path = "../rpc-api", features = ["wasm-client"] }
bitnames-types = { workspace = true }
ed25519-bip32 = "0.4.1"
futures = { workspace = true }
getrandom = { version = "0.2.10", features = ["js"] }
jsonrpsee = { workspace = true, features = ["wasm-client"] }
js-sys = "0.3.83"
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6.5"
ybc = "0.4.0"
yew = { version = "0.20", features = ["csr"] }
yew-hooks = "0.2.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.56"
web-sys = { version = "0.3.83", features = ["console", "Request", "Window"] }

[lib]
crate-type = ["cdylib"]
path = "lib.rs"